[package]
name = "sort_playlists"
version = "0.1.0"
authors = ["chensation"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
id3 = "0.5.3"
csv = "1.1.5"
htmlescape = "0.3.1"